# -*- coding: utf-8 -*-
"""palm_classification_augmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFvGJNG0r8jP6YQ03gO8MZpG8WQ5HADA

# **Deteksi Tingkat Kematangan Buah Kelapa Sawit dari Citra Tandan Menggunakan Convolutional Neural Network dengan Pendekatan Transfer Learning**

**Kelompok 10 - Kelas 2024E**
- Lailil Hidayanti (24031554036)
- Rahmawati Dian Pratiwi (24031554183)
- Nurlaila Lutfi Azizah (24051554205)

---

### Pipeline
```
1. Setup & Instalasi
2. Load Dataset (Roboflow)
3. Exploratory Data Analysis (EDA)
4. Preprocessing & DataLoader
5. Handling Class Imbalance
6. Transfer Learning (EfficientNetV2-S + Custom Head)
7. Two-Phase Fine-Tuning
   Phase 1: Feature Extraction (backbone frozen)
   Phase 2: Fine-Tuning (backbone unfrozen)
8. Evaluasi (Accuracy, F1, Confusion Matrix, Cohen's Kappa)
9. Grad-CAM Visualization
```

## **1. Setup & Instalasi**
"""

import os
import random
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from pathlib import Path
from collections import Counter
from PIL import Image
import warnings
warnings.filterwarnings('ignore')

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import timm

from sklearn.metrics import (
    classification_report, confusion_matrix,
    cohen_kappa_score, accuracy_score, f1_score
)

# Reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.deterministic = True

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {DEVICE}')
if torch.cuda.is_available():
    print(f'GPU: {torch.cuda.get_device_name(0)}')

"""## **2. Load Dataset dari Roboflow**"""

# 2. Load Dataset dari Google Drive
from google.colab import drive
drive.mount('/content/drive')

DATA_DIR  = Path("/content/drive/MyDrive/Project Akhir ML/Dataset_Kelapa_Sawit")
TRAIN_DIR = DATA_DIR / 'train'
VAL_DIR   = DATA_DIR / 'valid'
TEST_DIR  = DATA_DIR / 'test'

# Verifikasi
assert TRAIN_DIR.exists(), f"Train dir tidak ditemukan: {TRAIN_DIR}"
assert VAL_DIR.exists(),   f"Valid dir tidak ditemukan: {VAL_DIR}"
assert TEST_DIR.exists(),  f"Test  dir tidak ditemukan: {TEST_DIR}"

print(f'Dataset location : {DATA_DIR.resolve()}')
print(f'Train dir exists : {TRAIN_DIR.exists()}')
print(f'Valid dir exists : {VAL_DIR.exists()}')
print(f'Test  dir exists : {TEST_DIR.exists()}')

# ── Inventarisasi jumlah sampel per kelas per split ──────────────────────────
CLASS_NAMES = sorted([d.name for d in TRAIN_DIR.iterdir() if d.is_dir()])
NUM_CLASSES = len(CLASS_NAMES)
print(f'Kelas ({NUM_CLASSES}): {CLASS_NAMES}')

def count_per_class(split_dir):
    return {cls: len(list((split_dir / cls).glob('*.[jp][pn]g')) +
                      list((split_dir / cls).glob('*.jpeg')))
            for cls in CLASS_NAMES}

train_counts = count_per_class(TRAIN_DIR)
val_counts   = count_per_class(VAL_DIR)
test_counts  = count_per_class(TEST_DIR)

print('\n{:<15} {:>8} {:>8} {:>8}'.format('Kelas', 'Train', 'Valid', 'Test'))
print('-' * 43)
for cls in CLASS_NAMES:
    print(f'{cls:<15} {train_counts[cls]:>8} {val_counts[cls]:>8} {test_counts[cls]:>8}')
print('-' * 43)
print(f'{"TOTAL":<15} {sum(train_counts.values()):>8} {sum(val_counts.values()):>8} {sum(test_counts.values()):>8}')

"""## **3. Exploratory Data Analysis (EDA)**

### 3.1 Distribusi Dataset (Bar + Pie)
"""

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('Distribusi Dataset Kematangan Buah Kelapa Sawit', fontsize=14, fontweight='bold')

x = np.arange(len(CLASS_NAMES))
width = 0.25
colors = ['#2196F3', '#4CAF50', '#FF9800']

ax = axes[0]
bars1 = ax.bar(x - width, [train_counts[c] for c in CLASS_NAMES], width, label='Train', color=colors[0])
bars2 = ax.bar(x,         [val_counts[c]   for c in CLASS_NAMES], width, label='Valid', color=colors[1])
bars3 = ax.bar(x + width, [test_counts[c]  for c in CLASS_NAMES], width, label='Test',  color=colors[2])

for bars in [bars1, bars2, bars3]:
    for bar in bars:
        h = bar.get_height()
        if h > 0:
            ax.text(bar.get_x() + bar.get_width()/2, h + 3, str(int(h)),
                    ha='center', va='bottom', fontsize=8)

ax.set_xlabel('Kelas Kematangan')
ax.set_ylabel('Jumlah Gambar')
ax.set_title('Distribusi per Split (Train/Valid/Test)')
ax.set_xticks(x)
ax.set_xticklabels(CLASS_NAMES, rotation=20, ha='right')
ax.legend()
ax.grid(axis='y', alpha=0.3)

# Pie chart total
total_counts = {cls: train_counts[cls] + val_counts[cls] + test_counts[cls] for cls in CLASS_NAMES}
total_values = [total_counts[c] for c in CLASS_NAMES]
pie_colors   = plt.cm.Set3(np.linspace(0, 1, NUM_CLASSES))
wedges, texts, autotexts = axes[1].pie(
    total_values, labels=CLASS_NAMES, autopct='%1.1f%%',
    colors=pie_colors, startangle=140, pctdistance=0.75
)
axes[1].set_title('Proporsi Total Gambar per Kelas')

plt.tight_layout()
plt.savefig('eda_distribusi.png', dpi=150, bbox_inches='tight')
plt.show()

"""### 3.2 Imbalanced Analysis (Horizontal Bar)"""

fig, ax = plt.subplots(figsize=(10, 5))
total_train = sum(train_counts.values())
sorted_cls  = sorted(CLASS_NAMES, key=lambda c: train_counts[c], reverse=True)
vals        = [train_counts[c] for c in sorted_cls]
bar_colors  = ['#FF5252' if v == max(vals) else '#78909C' for v in vals]

bars = ax.barh(sorted_cls, vals, color=bar_colors, edgecolor='white', height=0.6)
for bar, v in zip(bars, vals):
    pct = v / total_train * 100
    ax.text(bar.get_width() + 5, bar.get_y() + bar.get_height()/2,
            f'{v} ({pct:.1f}%)', va='center', fontsize=10, fontweight='bold')

ax.set_xlabel('Jumlah Gambar (Train Set)')
ax.set_title('Distribusi Kelas — Analisis Imbalanced Data (Train Set)', fontweight='bold')
ax.set_xlim(0, max(vals) * 1.25)
ax.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.savefig('eda_imbalance.png', dpi=150, bbox_inches='tight')
plt.show()

imbalance_ratio = max(vals) / min(vals)
print(f'\nImbalance Ratio (max/min): {imbalance_ratio:.1f}x')
print(f'Kelas dominan  : {sorted_cls[0]} ({vals[0]} sampel)')
print(f'Kelas minoritas: {sorted_cls[-1]} ({vals[-1]} sampel)')

"""### **3.3 Contoh Gambar per Kelas**"""

fig, axes = plt.subplots(2, 3, figsize=(14, 9))
fig.suptitle('Contoh Gambar per Kelas Kematangan Kelapa Sawit', fontsize=14, fontweight='bold')

for ax, cls in zip(axes.flat, CLASS_NAMES):
    imgs = list((TRAIN_DIR / cls).glob('*.[jp][pn]g')) + \
           list((TRAIN_DIR / cls).glob('*.jpeg'))
    if imgs:
        img = Image.open(random.choice(imgs)).convert('RGB')
        ax.imshow(img)
    ax.set_title(f'{cls.upper()}\n({train_counts[cls]} gambar di train)',
                 fontsize=10, fontweight='bold',
                 bbox=dict(boxstyle='round,pad=0.3',
                           facecolor='#FF9800' if cls == 'ripe' else '#2196F3',
                           alpha=0.8, edgecolor='none'),
                 color='white')
    ax.axis('off')

plt.tight_layout()
plt.savefig('eda_sample_images.png', dpi=150, bbox_inches='tight')
plt.show()

from google.colab import drive
drive.flush_and_unmount()
drive.mount('/content/drive', force_remount=True)

"""### **3.4 Analisis Ukuran Gambar**"""

print('Mengecek ukuran gambar (sample 20 per kelas)...')
size_data = []
for cls in CLASS_NAMES:
    imgs = (list((TRAIN_DIR / cls).glob('*.[jp][pn]g')) +
            list((TRAIN_DIR / cls).glob('*.jpeg')))[:20]
    for p in imgs:
        w, h = Image.open(p).size
        size_data.append({'class': cls, 'width': w, 'height': h})

import pandas as pd
df_size = pd.DataFrame(size_data)
print(df_size.groupby('class')[['width','height']].describe())

fig, ax = plt.subplots(figsize=(8, 6))
palette = plt.cm.tab10(np.linspace(0, 1, NUM_CLASSES))
for i, cls in enumerate(CLASS_NAMES):
    sub = df_size[df_size['class'] == cls]
    ax.scatter(sub['width'], sub['height'], label=cls, color=palette[i], alpha=0.7, s=60)
ax.set_xlabel('Lebar (px)')
ax.set_ylabel('Tinggi (px)')
ax.set_title('Distribusi Ukuran Gambar per Kelas')
ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('eda_image_size.png', dpi=150, bbox_inches='tight')
plt.show()

"""### **3.5 Analisis RGB per Kelas**"""

print('Menghitung rata-rata RGB per kelas (sample 30 per kelas)')
rgb_stats = {}
for cls in CLASS_NAMES:
    imgs = (list((TRAIN_DIR / cls).glob('*.[jp][pn]g')) +
            list((TRAIN_DIR / cls).glob('*.jpeg')))[:30]
    r_vals, g_vals, b_vals = [], [], []
    for p in imgs:
        arr = np.array(Image.open(p).convert('RGB'), dtype=np.float32)
        r_vals.append(arr[:,:,0].mean())
        g_vals.append(arr[:,:,1].mean())
        b_vals.append(arr[:,:,2].mean())
    rgb_stats[cls] = (np.mean(r_vals), np.mean(g_vals), np.mean(b_vals))

fig, ax = plt.subplots(figsize=(12, 5))
x_pos   = np.arange(len(CLASS_NAMES))
w       = 0.25
ax.bar(x_pos - w, [rgb_stats[c][0] for c in CLASS_NAMES], w, label='Red',   color='#EF5350', edgecolor='white')
ax.bar(x_pos,     [rgb_stats[c][1] for c in CLASS_NAMES], w, label='Green', color='#66BB6A', edgecolor='white')
ax.bar(x_pos + w, [rgb_stats[c][2] for c in CLASS_NAMES], w, label='Blue',  color='#42A5F5', edgecolor='white')
ax.set_xticks(x_pos)
ax.set_xticklabels(CLASS_NAMES, rotation=20, ha='right')
ax.set_ylabel('Rata-rata Nilai Piksel (0-255)')
ax.set_title('Karakteristik Warna RGB Rata-rata per Kelas\n(berdasarkan sample gambar dari train set)')
ax.legend()
ax.set_ylim(0, 255)
ax.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig('eda_rgb.png', dpi=150, bbox_inches='tight')
plt.show()

"""## **4. Preprocessing & DataLoader**"""

# Hyperparameter
IMG_SIZE      = 224
BATCH_SIZE    = 32
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

# Transform ASLI (tanpa augmentasi)
transform_original = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
])

# SKENARIO 1 — Augmentasi
# Teknik: HorizontalFlip + RandomRotation + ColorJitter
# → Sama dengan augmentasi offline yang dilakukan Roboflow
# → Dataset Roboflow dibuat dengan augmentasi: flip, rotasi, brightness
# → Menerapkan hal yang sama → hasil augmentasi runtime bisa sangat
#   mirip dengan gambar val/test yang berasal dari original yang sama
transform_s1 = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(degrees=15),
    transforms.ColorJitter(
        brightness=0.3, contrast=0.3,
        saturation=0.1, hue=0.05
    ),
    transforms.ToTensor(),
    transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
])

# SKENARIO 2 — Augmentasi
# Teknik: GaussianBlur + RandomPerspective + RandomErasing
# → Mengubah frekuensi spatial (blur), geometri non-linear (perspektif),
#   dan menambah piksel acak (erasing) → fingerprint visual berbeda jauh
transform_s2 = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomApply([
        transforms.GaussianBlur(kernel_size=5, sigma=(0.5, 2.0))
    ], p=0.5),
    transforms.RandomApply([
        transforms.RandomPerspective(distortion_scale=0.3, p=1.0)
    ], p=0.4),
    transforms.ToTensor(),
    transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
    transforms.RandomErasing(
        p=0.3, scale=(0.02, 0.15), ratio=(0.3, 3.3), value='random'
    ),
])

ACTIVE_SCENARIO = 2

scenario_map = {
    0: ('Original — tanpa augmentasi',               transform_original),
    1: ('Skenario 1 (Flip/Rot/Color)',    transform_s1),
    2: ('Skenario 2 (Blur/Perspektif/Erase)', transform_s2),
}

scenario_name, transform_train = scenario_map[ACTIVE_SCENARIO]

# Val & Test SELALU pakai transform original (tanpa augmentasi)
transform_valtest = transform_original

train_dataset = datasets.ImageFolder(str(TRAIN_DIR), transform=transform_train)
val_dataset   = datasets.ImageFolder(str(VAL_DIR),   transform=transform_valtest)
test_dataset  = datasets.ImageFolder(str(TEST_DIR),  transform=transform_valtest)

CLASS_NAMES = train_dataset.classes # Class names are common across all datasets

print('RINGKASAN DATASET PER SKENARIO')
for key, (name, _) in scenario_map.items():
    print(f'\nSkenario aktif : {name}')
    print(f'Kelas          : {CLASS_NAMES}')
    print(f'Train: {len(train_dataset)} | Val: {len(val_dataset)} | Test: {len(test_dataset)}')

print(f'\nCatatan: Skenario yang dipilih untuk training berikutnya adalah Skenario {ACTIVE_SCENARIO}: {scenario_name}')

# Visualisasi Perbandingan Augmentasi
# Ambil 1 gambar dari kelas ripe, terapkan masing-masing transform 4×
import torch
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

def denorm(t):
    m = torch.tensor([0.485, 0.456, 0.406]).view(3,1,1)
    s = torch.tensor([0.229, 0.224, 0.225]).view(3,1,1)
    return (t * s + m).clamp(0, 1).permute(1, 2, 0).numpy()

sample_path = sorted((TRAIN_DIR / 'ripe').glob('*.jpg'))[0]
pil_img     = Image.open(sample_path).convert('RGB')

N_COL = 5  # original + 4 hasil augmentasi
fig, axes = plt.subplots(2, N_COL, figsize=(20, 8))
fig.suptitle('Perbandingan Augmentasi — 1 Gambar Asli, 4 Hasil per Skenario',
             fontsize=13, fontweight='bold')

# Baris 0: Skenario 1
axes[0][0].imshow(pil_img.resize((224, 224)))
axes[0][0].set_title('ORIGINAL', fontweight='bold', fontsize=11)
axes[0][0].set_ylabel('SKENARIO 1\n(Berisiko)', color='#C44E52',
                      fontsize=11, fontweight='bold', rotation=90, labelpad=8)
axes[0][0].axis('off')
for j in range(1, N_COL):
    axes[0][j].imshow(denorm(transform_s1(pil_img)))
    axes[0][j].set_title(f'S1 #{j}\nFlip/Rot/Color', color='#C44E52', fontsize=9)
    axes[0][j].axis('off')

# Baris 1: Skenario 2
axes[1][0].imshow(pil_img.resize((224, 224)))
axes[1][0].set_title('ORIGINAL', fontweight='bold', fontsize=11)
axes[1][0].set_ylabel('SKENARIO 2\n(Aman)', color='#2ca02c',
                      fontsize=11, fontweight='bold', rotation=90, labelpad=8)
axes[1][0].axis('off')
for j in range(1, N_COL):
    axes[1][j].imshow(denorm(transform_s2(pil_img)))
    axes[1][j].set_title(f'S2 #{j}\nBlur/Perspektif/Erase', color='#2ca02c', fontsize=9)
    axes[1][j].axis('off')

plt.tight_layout()
plt.savefig('viz_augmentasi_perbandingan.png', dpi=120, bbox_inches='tight')
plt.show()
print('Perhatikan:')
print('  S1 → terlihat seperti versi flip/rotasi gambar yang mungkin sudah ada di dataset')
print('  S2 → blur, distorsi perspektif, atau area terhapus — tidak mungkin ada di dataset asli')

"""---
## 🔍 Deteksi Augmentation Leakage

> Dua skenario augmentasi diuji menggunakan **Perceptual Hash (pHash)** untuk mendeteksi apakah hasil augmentasi runtime menghasilkan gambar yang terlalu mirip dengan gambar val/test.
>
> Metode: simulasikan augmentasi pada sampel train → bandingkan fingerprint visual dengan seluruh val+test → flagged jika hamming distance ≤ 10 (≥84% mirip secara visual).

### 🔴 Skenario 1 — Deteksi Leakage (Augmentasi Berisiko)
"""

# DETEKSI AUGMENTATION LEAKAGE — SKENARIO 1 (BERISIKO)
# Metode: Perceptual Hash (pHash) via DCT
# Cara kerja pHash:
#   1. Gambar → grayscale → resize 32×32
#   2. DCT 2D → ambil blok 8×8 frekuensi rendah (64 nilai)
#   3. Setiap nilai > median → bit 1, ≤ median → bit 0
#   4. Hasil: 64-bit fingerprint
# Hamming distance = jumlah bit berbeda (0=identik, 64=sangat berbeda)
# Threshold leakage: ≤ 6 bit (≥84% mirip secara visual)

# Simulasi: terapkan transform_s1 ke N gambar train, hitung pHash-nya,
# bandingkan dengan pHash semua gambar val+test. Kalau hamming ≤ 6
# → augmentasi menghasilkan gambar yang "terlihat seperti" val/test

from scipy.fftpack import dct as scipy_dct
from pathlib import Path
from PIL import Image
import numpy as np, random, torch, matplotlib.pyplot as plt

HAMMING_THRESH = 6  # ≤6/64 bit = ≥% mirip

def phash(img_input, hash_size=8):
    """Perceptual hash via DCT. Menerima Path atau PIL.Image."""
    img = (Image.open(img_input) if isinstance(img_input, (str, Path))
           else img_input).convert('L')
    img     = img.resize((hash_size * 4, hash_size * 4), Image.LANCZOS)
    pixels  = np.array(img, dtype=float)
    dct_2d  = scipy_dct(scipy_dct(pixels, axis=1, norm='ortho'), axis=0, norm='ortho')
    dct_low = dct_2d[:hash_size, :hash_size]
    return (dct_low > np.median(dct_low)).flatten()

def hamming(h1, h2): return int(np.sum(h1 != h2))

def denorm(t):
    m = torch.tensor([0.485, 0.456, 0.406]).view(3,1,1)
    s = torch.tensor([0.229, 0.224, 0.225]).view(3,1,1)
    return (t * s + m).clamp(0, 1).permute(1, 2, 0).numpy()

def get_files(root):
    return [p for p in Path(root).rglob('*')
            if p.suffix.lower() in {'.jpg', '.jpeg', '.png'}]

print('='*60)
print('  CEK AUGMENTATION LEAKAGE — SKENARIO 1')
print('  Augmentasi: HorizontalFlip + Rotation±15° + ColorJitter')
print('='*60)

train_files = get_files(TRAIN_DIR)
val_files   = get_files(VAL_DIR)
test_files  = get_files(TEST_DIR)
print(f'\nFile: Train={len(train_files)} | Val={len(val_files)} | Test={len(test_files)}')

# Hitung pHash semua file val+test print('Menghitung pHash val+test...')
val_hashes  = [(p, phash(p)) for p in val_files]
test_hashes = [(p, phash(p)) for p in test_files]
ref_hashes  = val_hashes + test_hashes
print(f'  Selesai: {len(ref_hashes)} referensi hash')

# Simulasi augmentasi S1
N_TRAIN_SAMPLE = 80    # gambar train yang disimulasikan
N_AUG_PER_IMG  = 8     # augmentasi per gambar

sim_files = random.sample(train_files, min(N_TRAIN_SAMPLE, len(train_files)))
leaked_s1 = []  # list of dict: {train_path, ref_path, ref_split, hamming, aug_tensor, ref_pil}

print(f'\nSimulasi: {N_TRAIN_SAMPLE} gambar × {N_AUG_PER_IMG} augmentasi = ' \
      f'{N_TRAIN_SAMPLE * N_AUG_PER_IMG} citra diuji...')

for tp in sim_files:
    pil = Image.open(tp).convert('RGB')
    for _ in range(N_AUG_PER_IMG):
        aug_t    = transform_s1(pil)
        aug_np   = (denorm(aug_t) * 255).astype(np.uint8)
        aug_pil  = Image.fromarray(aug_np)
        aug_hash = phash(aug_pil)

        for rp, rh in ref_hashes:
            d = hamming(aug_hash, rh)
            if d <= HAMMING_THRESH:
                split = 'val' if rp in [x[0] for x in val_hashes] else 'test'
                leaked_s1.append({
                    'train_path'  : tp,
                    'ref_path'    : rp,
                    'ref_split'   : split,
                    'hamming'     : d,
                    'aug_tensor'  : aug_t,
                    'ref_pil'     : Image.open(rp).convert('RGB'),
                })

print(f'\nHasil: {len(leaked_s1)} pasangan leakage dari ' \
      f'{N_TRAIN_SAMPLE * N_AUG_PER_IMG} augmentasi yang diuji')

# Verdict
if leaked_s1:
    print(f'\n LEAKAGE TERDETEKSI — Skenario 1')
    val_leak  = sum(1 for x in leaked_s1 if x['ref_split'] == 'val')
    test_leak = sum(1 for x in leaked_s1 if x['ref_split'] == 'test')
    print(f'   → {val_leak} ke Val set | {test_leak} ke Test set')
    ham_vals = [x['hamming'] for x in leaked_s1]
    print(f'   → Hamming distance: min={min(ham_vals)}, max={max(ham_vals)}, '
          f'avg={np.mean(ham_vals):.1f}')
else:
    print(' Tidak ada leakage terdeteksi pada sampel ini')
    print(' (Coba naikkan N_TRAIN_SAMPLE atau N_AUG_PER_IMG untuk confidence lebih tinggi)')

# Visualisasi citra yang bocor
if leaked_s1:
    N_SHOW = min(6, len(leaked_s1))
    # Urutkan dari hamming distance terkecil (paling mirip dulu)
    show_cases = sorted(leaked_s1, key=lambda x: x['hamming'])[:N_SHOW]

    fig, axes = plt.subplots(3, N_SHOW, figsize=(N_SHOW * 3.5, 10))
    fig.suptitle(
        f'Skenario 1 — Contoh Augmentation Leakage (Hamming \u2264 {HAMMING_THRESH})\n'
        f'Kiri\u2192Kanan: makin kecil hamming distance = makin mirip',
        fontsize=12, fontweight='bold'
    )

    for col, case in enumerate(show_cases):
        # Baris 0: gambar train original
        orig_pil = Image.open(case['train_path']).convert('RGB').resize((224, 224))
        axes[0][col].imshow(orig_pil)
        cls_name = case['train_path'].parent.name
        axes[0][col].set_title(f'TRAIN ORIGINAL\n[{cls_name}]',
                               fontweight='bold', color='#1f77b4')
        axes[0][col].axis('off')

        # Baris 1: hasil augmentasi S1 yang bocor
        axes[1][col].imshow(denorm(case['aug_tensor']))
        axes[1][col].set_title(f'AUGMENTED (S1)\nFlip/Rot/Color',
                               color='#C44E52', fontweight='bold')
        axes[1][col].axis('off')
        # Tanda "bocor"
        axes[1][col].text(0.5, -0.08, f'\u2b07 dist={case["hamming"]}',
                          transform=axes[1][col].transAxes,
                          ha='center', fontsize=10, color='red', fontweight='bold')

        # Baris 2: gambar val/test yang mirip
        ref_img = case['ref_pil'].resize((224, 224))
        axes[2][col].imshow(ref_img)
        ref_cls = case['ref_path'].parent.name
        axes[2][col].set_title(
            f'{case["ref_split"].upper()} SET\n[{ref_cls}]\n'
            f'hamming={case["hamming"]}',
            fontsize=9, color='#2ca02c', fontweight='bold'
        )
        axes[2][col].axis('off')

    # Label baris
    for ax, label, color in zip(
        [axes[0][0], axes[1][0], axes[2][0]],
        ['Gambar Train\nOriginal', 'Hasil Augmentasi S1\n(yang bocor)', 'Gambar Val/Test\n(sangat mirip)'],
        ['#1f77b4', '#C44E52', '#2ca02c']
    ):
        ax.set_ylabel(label, rotation=0, labelpad=90, va='center',
                      fontsize=9, color=color, fontweight='bold')

    plt.tight_layout()
    plt.savefig('leakage_s1_contoh.png', dpi=120, bbox_inches='tight')
    plt.show()
    print(f'\n Interpretasi:')
    print(f'   Baris tengah = hasil augmentasi S1 dari gambar train')
    print(f'   Baris bawah  = gambar val/test yang punya fingerprint mirip')
    print(f'   Karena dataset Roboflow dibuat dengan augmentasi serupa (flip/rotasi),')
    print(f'   augmentasi runtime kita menghasilkan varian yang sudah pernah "dilihat"')
    print(f'   model dalam bentuk val/test \u2192 evaluasi menjadi tidak fair')
print('='*60)

"""### 🟢 Skenario 2 — Deteksi Leakage (Augmentasi Aman)"""

# DETEKSI AUGMENTATION LEAKAGE — SKENARIO 2 (AMAN)
# Prosedur identik dengan S1, tapi menggunakan transform_s2
# Ekspektasi: leakage JAUH lebih sedikit atau nol karena:
#   - GaussianBlur → mengubah frekuensi tinggi → DCT berbeda
#   - RandomPerspective → transformasi geometri non-linear
#   - RandomErasing → piksel acak mengubah hash secara tidak terduga

print('='*60)
print('  CEK AUGMENTATION LEAKAGE — SKENARIO 2')
print('  Augmentasi: GaussianBlur + RandomPerspective + RandomErasing')
print('='*60)

# Gunakan file dan ref_hashes yang sama dari S1
leaked_s2 = []

print(f'\nSimulasi: {N_TRAIN_SAMPLE} gambar × {N_AUG_PER_IMG} augmentasi = '
      f'{N_TRAIN_SAMPLE * N_AUG_PER_IMG} citra diuji...')

for tp in sim_files:  # gambar yang sama dengan S1 untuk perbandingan fair
    pil = Image.open(tp).convert('RGB')
    for _ in range(N_AUG_PER_IMG):
        aug_t    = transform_s2(pil)
        aug_np   = (denorm(aug_t) * 255).astype(np.uint8)
        aug_pil  = Image.fromarray(aug_np)
        aug_hash = phash(aug_pil)

        for rp, rh in ref_hashes:
            d = hamming(aug_hash, rh)
            if d <= HAMMING_THRESH:
                split = 'val' if rp in [x[0] for x in val_hashes] else 'test'
                leaked_s2.append({
                    'train_path' : tp,
                    'ref_path'   : rp,
                    'ref_split'  : split,
                    'hamming'    : d,
                    'aug_tensor' : aug_t,
                    'ref_pil'    : Image.open(rp).convert('RGB'),
                })

print(f'\nHasil: {len(leaked_s2)} pasangan leakage dari '
      f'{N_TRAIN_SAMPLE * N_AUG_PER_IMG} augmentasi yang diuji')

if leaked_s2:
    print(f'\n Ada leakage terdeteksi')
    ham_vals2 = [x['hamming'] for x in leaked_s2]
    print(f'   → Hamming distance: min={min(ham_vals2)}, max={max(ham_vals2)}, '
          f'avg={np.mean(ham_vals2):.1f}')
    print(f'   → Biasanya ini karena RandomErasing menghasilkan gambar ber-frekuensi')
    print(f'     rendah yang kebetulan mirip beberapa gambar dataset.')
    print(f'     Secara semantik (konten visual) gambar berbeda jauh.')
else:
    print('\n TIDAK ADA LEAKAGE — Skenario 2')
    print('   Augmentasi S2 menghasilkan fingerprint visual yang berbeda jauh dari val/test')

# Visualisasi jika ada
if leaked_s2:
    N_SHOW2 = min(4, len(leaked_s2))
    show_cases2 = sorted(leaked_s2, key=lambda x: x['hamming'])[:N_SHOW2]

    fig, axes = plt.subplots(3, N_SHOW2, figsize=(N_SHOW2 * 3.5, 10))
    fig.suptitle(
        f'Skenario 2 — Leakage yang Masih Terdeteksi (jika ada)\n'
        f'Perhatikan perbedaan visual yang lebih besar dibanding S1',
        fontsize=12, fontweight='bold'
    )
    for col, case in enumerate(show_cases2):
        orig_pil = Image.open(case['train_path']).convert('RGB').resize((224,224))
        axes[0][col].imshow(orig_pil)
        axes[0][col].set_title(f'TRAIN ORIGINAL\n[{case["train_path"].parent.name}]',
                               fontsize=9, fontweight='bold', color='#1f77b4')
        axes[0][col].axis('off')

        axes[1][col].imshow(denorm(case['aug_tensor']))
        axes[1][col].set_title('AUGMENTED (S2)\nBlur/Perspektif/Erase',
                               fontsize=9, color='#2ca02c', fontweight='bold')
        axes[1][col].axis('off')
        axes[1][col].text(0.5, -0.08, f'⬇ dist={case["hamming"]}',
                          transform=axes[1][col].transAxes,
                          ha='center', fontsize=10, color='orange', fontweight='bold')

        ref_img = case['ref_pil'].resize((224,224))
        axes[2][col].imshow(ref_img)
        axes[2][col].set_title(
            f'{case["ref_split"].upper()} SET\n[{case["ref_path"].parent.name}]\n'
            f'hamming={case["hamming"]}',
            fontsize=9, color='#555', fontweight='bold'
        )
        axes[2][col].axis('off')

    plt.tight_layout()
    plt.savefig('leakage_s2_contoh.png', dpi=120, bbox_inches='tight')
    plt.show()

# Perbandingan distribusi hamming distance S1 vs S2
print('\nDistribusi Hamming Distance: S1 vs S2 vs Dataset Asli ')
print('   (Seberapa berbeda augmented images dari val/test secara visual)')

def sample_hamming(aug_transform, src_files, ref_h, n=40, k=5):
    dists = []
    for tp in random.sample(src_files, min(n, len(src_files))):
        pil = Image.open(tp).convert('RGB')
        for _ in range(k):
            aug_t  = aug_transform(pil)
            aug_np = (denorm(aug_t) * 255).astype(np.uint8)
            ah     = phash(Image.fromarray(aug_np))
            for rp, rh in ref_h[:30]:
                dists.append(hamming(ah, rh))
    return dists

dists_s1   = sample_hamming(transform_s1, train_files, ref_hashes[:100])
dists_s2   = sample_hamming(transform_s2, train_files, ref_hashes[:100])
dists_base = [hamming(phash(tp), rh)
              for tp in random.sample(train_files, 40)
              for _, rh in ref_hashes[:30]]

fig, ax = plt.subplots(figsize=(13, 5))
bins = range(0, 65, 2)
ax.hist(dists_s1,   bins=bins, alpha=0.6, density=True, color='#C44E52',
        label=f'S1 Berisiko (Flip/Rot/Color)  — mean={np.mean(dists_s1):.1f}')
ax.hist(dists_s2,   bins=bins, alpha=0.6, density=True, color='#2ca02c',
        label=f'S2 Aman (Blur/Perspektif/Erase) — mean={np.mean(dists_s2):.1f}')
ax.hist(dists_base, bins=bins, alpha=0.5, density=True, color='#4C72B0',
        label=f'Dataset Asli (tanpa augmentasi) — mean={np.mean(dists_base):.1f}')
ax.axvline(HAMMING_THRESH, color='red', lw=2, linestyle='--',
           label=f'Batas leakage ({HAMMING_THRESH} bit)')
ax.set_xlabel('Hamming Distance (0 = identik, 64 = sangat berbeda)', fontsize=12)
ax.set_ylabel('Densitas', fontsize=12)
ax.set_title(
    'Distribusi Jarak Visual: Augmented Train → Val/Test\n'
    'Kurva lebih ke KIRI = lebih mirip val/test = lebih berisiko leakage',
    fontsize=12
)
ax.legend(fontsize=10)
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('hamming_dist_s1_vs_s2.png', dpi=130, bbox_inches='tight')
plt.show()

# Tabel ringkasan final
print('\n' + '='*60)
print('  RINGKASAN PERBANDINGAN LEAKAGE S1 vs S2')
print('='*60)
print(f'  {"Metrik":<40} {"S1":>8} {"S2":>8}')
print(f'\n  {"Leakage terdeteksi (simulasi)":<40} {len(leaked_s1):>8} {len(leaked_s2):>8}')
print(f'  {"Avg Hamming dist ke val/test":<40} {np.mean(dists_s1):>8.1f} {np.mean(dists_s2):>8.1f}')
lk_rate_s1 = len(leaked_s1) / (N_TRAIN_SAMPLE * N_AUG_PER_IMG) * 100
lk_rate_s2 = len(leaked_s2) / (N_TRAIN_SAMPLE * N_AUG_PER_IMG) * 100
print(f'  {"Leak rate (%)":<40} {lk_rate_s1:>7.1f}% {lk_rate_s2:>7.1f}%')
print('='*60)

"""---
## ⚙️ Pilih Skenario Aktif untuk Training

## **5. Handling Class Imbalance**

### 5.1 Hitung class weights (invers frekuensi)
"""

# Class weights dihitung dari distribusi ASLI (bukan dari augmentasi)
# → distribusi kelas tidak berubah karena augmentasi tidak menambah/mengurangi file
targets     = [s[1] for s in train_dataset.samples]
class_count = Counter(targets)
total_train = len(targets)

class_weights = torch.tensor(
    [total_train / (NUM_CLASSES * class_count[i]) for i in range(NUM_CLASSES)],
    dtype=torch.float
).to(DEVICE)

print('Class weights:')
for i, cls in enumerate(CLASS_NAMES):
    print(f'  {cls:<15}: {class_weights[i].item():.4f}  (n={class_count[i]})')

"""### 5.2 DataLoaders"""

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True,
                          num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False,
                          num_workers=2, pin_memory=True)
test_loader  = DataLoader(test_dataset,  batch_size=BATCH_SIZE, shuffle=False,
                          num_workers=2, pin_memory=True)

print(f'Train batches: {len(train_loader)} | Val batches: {len(val_loader)} | Test batches: {len(test_loader)}')

"""### 5.3 Focal Loss

"""

class FocalLoss(nn.Module):
    """
    Focal Loss (Lin et al., 2017) dengan class weights + label smoothing.
    FL(pt) = -alpha_t * (1 - pt)^gamma * log(pt)
    """
    def __init__(self, alpha=None, gamma=2.0, label_smoothing=0.1, reduction='mean'):
        super().__init__()
        self.alpha           = alpha
        self.gamma           = gamma
        self.label_smoothing = label_smoothing
        self.reduction       = reduction

    def forward(self, logits, targets):
        n_cls = logits.size(1)
        # Label smoothing
        with torch.no_grad():
            smooth_targets = torch.zeros_like(logits)
            smooth_targets.fill_(self.label_smoothing / (n_cls - 1))
            smooth_targets.scatter_(1, targets.unsqueeze(1), 1.0 - self.label_smoothing)

        log_probs = torch.log_softmax(logits, dim=1)
        probs     = torch.exp(log_probs)

        # (1 - pt)^gamma term
        pt      = (probs * smooth_targets).sum(dim=1)
        focal_w = (1 - pt) ** self.gamma

        # Cross-entropy with smooth targets
        ce_loss = -(smooth_targets * log_probs).sum(dim=1)
        loss    = focal_w * ce_loss

        # Class weights
        if self.alpha is not None:
            alpha_t = self.alpha[targets]
            loss    = alpha_t * loss

        return loss.mean() if self.reduction == 'mean' else loss.sum()

criterion = FocalLoss(alpha=class_weights, gamma=2.0, label_smoothing=0.1)
print('FocalLoss initialized ✓')

"""## **6. Transfer Learning EfficientNetV2-S + Custom Head**"""

class PalmRipenessModel(nn.Module):
    def __init__(self, num_classes=6, dropout=0.4):
        super().__init__()
        # Load backbone dengan timm (ImageNet-21k pretrained)
        self.backbone = timm.create_model(
            'tf_efficientnetv2_s.in21k',
            pretrained=True,
            num_classes=0,           # hapus classifier bawaan
            global_pool='avg'        # GlobalAvgPool
        )
        in_features = self.backbone.num_features

        # Custom classification head
        self.head = nn.Sequential(
            nn.Dropout(p=dropout),
            nn.Linear(in_features, 256),
            nn.BatchNorm1d(256),
            nn.ReLU(inplace=True),
            nn.Linear(256, num_classes)
        )

    def freeze_backbone(self):
        """Phase 1: bekukan seluruh backbone"""
        for param in self.backbone.parameters():
            param.requires_grad = False

    def unfreeze_backbone(self):
        """Phase 2: buka semua lapisan"""
        for param in self.backbone.parameters():
            param.requires_grad = True

    def forward(self, x):
        features = self.backbone(x)
        return self.head(features)


model = PalmRipenessModel(num_classes=NUM_CLASSES).to(DEVICE)

# Ringkasan parameter
total_params   = sum(p.numel() for p in model.parameters())
trainable_head = sum(p.numel() for p in model.head.parameters())
print(f'Total params      : {total_params:,}')
print(f'Head params       : {trainable_head:,}')
print(f'Backbone params   : {total_params - trainable_head:,}')

"""## **7. Two-Phase Fine-Tuning**"""

# Utility: training & validation loop
from tqdm.notebook import tqdm

def train_epoch(model, loader, optimizer, criterion, device):
    model.train()
    total_loss, correct, total = 0.0, 0, 0
    for imgs, labels in tqdm(loader, desc='  Train', leave=False):
        imgs, labels = imgs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(imgs)
        loss    = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * imgs.size(0)
        preds      = outputs.argmax(dim=1)
        correct    += (preds == labels).sum().item()
        total      += imgs.size(0)
    return total_loss / total, correct / total


@torch.no_grad()
def val_epoch(model, loader, criterion, device):
    model.eval()
    total_loss, all_preds, all_labels = 0.0, [], []
    for imgs, labels in tqdm(loader, desc='  Valid', leave=False):
        imgs, labels = imgs.to(device), labels.to(device)
        outputs = model(imgs)
        loss    = criterion(outputs, labels)
        total_loss += loss.item() * imgs.size(0)
        all_preds.extend(outputs.argmax(dim=1).cpu().numpy())
        all_labels.extend(labels.cpu().numpy())
    avg_loss = total_loss / len(loader.dataset)
    macro_f1 = f1_score(all_labels, all_preds, average='macro', zero_division=0)
    accuracy = accuracy_score(all_labels, all_preds)
    return avg_loss, macro_f1, accuracy


def plot_history(history, title='Training History'):
    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    fig.suptitle(title, fontsize=13, fontweight='bold')
    metrics = [
        ('train_loss', 'val_loss',     'Loss',      'Loss'),
        ('train_acc',  'val_acc',      'Accuracy',  'Accuracy'),
        (None,         'val_macro_f1', 'Macro F1',  'F1 Score'),
    ]
    for ax, (tr_key, vl_key, label, ylabel) in zip(axes, metrics):
        if tr_key:
            ax.plot(history[tr_key], label='Train', color='#2196F3', linewidth=2)
        ax.plot(history[vl_key], label='Valid', color='#FF5722', linewidth=2)
        ax.set_title(label)
        ax.set_xlabel('Epoch')
        ax.set_ylabel(ylabel)
        ax.legend()
        ax.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(f'history_{title.replace(" ","_").lower()}.png', dpi=150, bbox_inches='tight')
    plt.show()

print('Utility functions defined ✓')

"""### **PHASE 1 Feature Extraction (backbone FROZEN)**"""

PHASE1_EPOCHS  = 12
PHASE1_LR      = 1e-3
PATIENCE       = 7
CHECKPOINT_P1  = 'best_phase1.pth'

model.freeze_backbone()
trainable_p1 = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f'Phase 1 — Trainable params: {trainable_p1:,} (head only)')

optimizer_p1 = optim.AdamW(filter(lambda p: p.requires_grad, model.parameters()),
                            lr=PHASE1_LR, weight_decay=1e-4)
scheduler_p1 = optim.lr_scheduler.OneCycleLR(
    optimizer_p1, max_lr=PHASE1_LR,
    steps_per_epoch=len(train_loader), epochs=PHASE1_EPOCHS
)

history_p1  = {'train_loss':[], 'train_acc':[], 'val_loss':[], 'val_acc':[], 'val_macro_f1':[]}
best_f1_p1  = 0.0
patience_cnt = 0

print('PHASE 1: Feature Extraction')

for epoch in range(1, PHASE1_EPOCHS + 1):
    tr_loss, tr_acc = train_epoch(model, train_loader, optimizer_p1, criterion, DEVICE)
    vl_loss, vl_f1, vl_acc = val_epoch(model, val_loader, criterion, DEVICE)
    scheduler_p1.step()

    history_p1['train_loss'].append(tr_loss)
    history_p1['train_acc'].append(tr_acc)
    history_p1['val_loss'].append(vl_loss)
    history_p1['val_acc'].append(vl_acc)
    history_p1['val_macro_f1'].append(vl_f1)

    flag = ''
    if vl_f1 > best_f1_p1:
        best_f1_p1  = vl_f1
        patience_cnt = 0
        torch.save(model.state_dict(), CHECKPOINT_P1)
        flag = '  ✓ saved'
    else:
        patience_cnt += 1

    print(f'Epoch [{epoch:2d}/{PHASE1_EPOCHS}] '
          f'Train Loss: {tr_loss:.4f} Acc: {tr_acc:.4f} | '
          f'Val Loss: {vl_loss:.4f} Acc: {vl_acc:.4f} F1: {vl_f1:.4f}{flag}')

    if patience_cnt >= PATIENCE:
        print(f'Early stopping at epoch {epoch}')
        break

plot_history(history_p1, 'Phase 1 — Feature Extraction')
print(f'\nBest Val Macro F1 (Phase 1): {best_f1_p1:.4f}')

"""### PHASE 2 Fine-Tuning (ALL layers UNFROZEN)"""

PHASE2_EPOCHS  = 40
PHASE2_LR      = 1e-4
CHECKPOINT_P2  = 'best_phase2.pth'

# Load best phase-1 weights sebelum fine-tuning
model.load_state_dict(torch.load(CHECKPOINT_P1, map_location=DEVICE))
model.unfreeze_backbone()
trainable_p2 = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f'Phase 2 — Trainable params: {trainable_p2:,} (all layers)')

optimizer_p2 = optim.AdamW(model.parameters(), lr=PHASE2_LR, weight_decay=1e-4)
scheduler_p2 = optim.lr_scheduler.CosineAnnealingLR(
    optimizer_p2, T_max=PHASE2_EPOCHS, eta_min=1e-6
)

history_p2   = {'train_loss':[], 'train_acc':[], 'val_loss':[], 'val_acc':[], 'val_macro_f1':[]}
best_f1_p2   = 0.0
patience_cnt  = 0

print('PHASE 2: Fine-Tuning')
for epoch in range(1, PHASE2_EPOCHS + 1):
    tr_loss, tr_acc = train_epoch(model, train_loader, optimizer_p2, criterion, DEVICE)
    vl_loss, vl_f1, vl_acc = val_epoch(model, val_loader, criterion, DEVICE)
    scheduler_p2.step()

    history_p2['train_loss'].append(tr_loss)
    history_p2['train_acc'].append(tr_acc)
    history_p2['val_loss'].append(vl_loss)
    history_p2['val_acc'].append(vl_acc)
    history_p2['val_macro_f1'].append(vl_f1)

    flag = ''
    if vl_f1 > best_f1_p2:
        best_f1_p2   = vl_f1
        patience_cnt  = 0
        torch.save(model.state_dict(), CHECKPOINT_P2)
        flag = '  ✓ saved'
    else:
        patience_cnt += 1

    print(f'Epoch [{epoch:2d}/{PHASE2_EPOCHS}] '
          f'Train Loss: {tr_loss:.4f} Acc: {tr_acc:.4f} | '
          f'Val Loss: {vl_loss:.4f} Acc: {vl_acc:.4f} F1: {vl_f1:.4f}{flag}')

    if patience_cnt >= PATIENCE:
        print(f'Early stopping at epoch {epoch}')
        break

plot_history(history_p2, 'Phase 2 Fine-Tuning')
print(f'\nBest Val Macro F1 (Phase 2): {best_f1_p2:.4f}')

"""## **8. Evaluasi pada Test Set**"""

# Load best checkpoint
model.load_state_dict(torch.load(CHECKPOINT_P2, map_location=DEVICE))
model.eval()

all_preds, all_labels, all_probs = [], [], []
with torch.no_grad():
    for imgs, labels in tqdm(test_loader, desc='Evaluating'):
        imgs   = imgs.to(DEVICE)
        logits = model(imgs)
        probs  = torch.softmax(logits, dim=1)
        preds  = logits.argmax(dim=1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.numpy())
        all_probs.extend(probs.cpu().numpy())

all_preds  = np.array(all_preds)
all_labels = np.array(all_labels)

# Metrik utama
acc      = accuracy_score(all_labels, all_preds)
macro_f1 = f1_score(all_labels, all_preds, average='macro',    zero_division=0)
micro_f1 = f1_score(all_labels, all_preds, average='micro',    zero_division=0)
kappa    = cohen_kappa_score(all_labels, all_preds)

print('=' * 55)
print('HASIL EVALUASI PADA TEST SET')
print('=' * 55)
print(f'  Accuracy       : {acc:.4f}  ({acc*100:.2f}%)')
print(f'  Macro F1-Score : {macro_f1:.4f}')
print(f'  Micro F1-Score : {micro_f1:.4f}')
print(f"  Cohen's Kappa  : {kappa:.4f}")
print('=' * 55)

print('\nClassification Report:')
print(classification_report(all_labels, all_preds,
                             target_names=CLASS_NAMES,
                             zero_division=0))

# Confusion Matrix
cm = confusion_matrix(all_labels, all_preds)
cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

for ax, data, fmt, title in zip(
    axes,
    [cm, cm_norm],
    ['d', '.2f'],
    ['Confusion Matrix (Count)', 'Confusion Matrix (Normalized)']
):
    sns.heatmap(data, annot=True, fmt=fmt, cmap='Blues',
                xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES,
                linewidths=0.5, ax=ax, cbar_kws={'shrink': 0.8})
    ax.set_xlabel('Predicted', fontsize=11)
    ax.set_ylabel('Actual', fontsize=11)
    ax.set_title(title, fontsize=12, fontweight='bold')
    ax.set_xticklabels(CLASS_NAMES, rotation=30, ha='right')
    ax.set_yticklabels(CLASS_NAMES, rotation=0)

plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()

# Per-Class Metrics Bar Chart
from sklearn.metrics import precision_score, recall_score

precision = precision_score(all_labels, all_preds, average=None, zero_division=0)
recall    = recall_score(all_labels, all_preds, average=None, zero_division=0)
f1_per    = f1_score(all_labels, all_preds, average=None, zero_division=0)

fig, ax = plt.subplots(figsize=(12, 5))
x   = np.arange(len(CLASS_NAMES))
w   = 0.25
ax.bar(x - w, precision, w, label='Precision', color='#42A5F5', edgecolor='white')
ax.bar(x,     recall,    w, label='Recall',    color='#66BB6A', edgecolor='white')
ax.bar(x + w, f1_per,    w, label='F1-Score',  color='#FF7043', edgecolor='white')

for i, (p, r, f) in enumerate(zip(precision, recall, f1_per)):
    for val, offset in [(p, -w), (r, 0), (f, w)]:
        ax.text(i + offset, val + 0.01, f'{val:.2f}', ha='center', va='bottom', fontsize=8)

ax.set_xticks(x)
ax.set_xticklabels(CLASS_NAMES, rotation=20, ha='right')
ax.set_ylim(0, 1.15)
ax.set_ylabel('Score')
ax.set_title('Per-Class Precision, Recall, F1-Score', fontweight='bold')
ax.legend()
ax.grid(axis='y', alpha=0.3)

# Garis target
ax.axhline(0.75, color='red',   linestyle='--', alpha=0.5, label='Target Minoritas (0.75)')
ax.axhline(0.85, color='green', linestyle='--', alpha=0.5, label='Target Accuracy (0.85)')
ax.legend()
plt.tight_layout()
plt.savefig('per_class_metrics.png', dpi=150, bbox_inches='tight')
plt.show()

"""## **9. Grad-CAM Visualization**"""

import sys
!{sys.executable} -m pip install grad-cam > /dev/null
from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget
from pytorch_grad_cam.utils.image import show_cam_on_image

# Target layer: last conv block of EfficientNetV2-S
# timm model: backbone.blocks[-1][-1]
target_layers = [model.backbone.blocks[-1][-1]]
cam = GradCAM(model=model, target_layers=target_layers)

# Ambil 1 contoh per kelas dari test set
def denormalize(tensor):
    mean = torch.tensor(IMAGENET_MEAN).view(3,1,1)
    std  = torch.tensor(IMAGENET_STD).view(3,1,1)
    return (tensor * std + mean).clamp(0, 1)

fig, axes = plt.subplots(2, NUM_CLASSES, figsize=(18, 7))
fig.suptitle('Grad-CAM Visualization — Area Fokus Model per Kelas', fontsize=13, fontweight='bold')

for cls_idx, cls_name in enumerate(CLASS_NAMES):
    # Cari sample dari test set
    sample_idx = next((i for i, (_, lbl) in enumerate(test_dataset.samples) if lbl == cls_idx), None)
    if sample_idx is None:
        continue

    img_tensor, _ = test_dataset[sample_idx]
    input_tensor  = img_tensor.unsqueeze(0).to(DEVICE)
    rgb_img       = denormalize(img_tensor).permute(1, 2, 0).numpy()

    targets       = [ClassifierOutputTarget(cls_idx)]
    grayscale_cam = cam(input_tensor=input_tensor, targets=targets)
    cam_image     = show_cam_on_image(rgb_img, grayscale_cam[0], use_rgb=True)

    # Original
    axes[0, cls_idx].imshow(rgb_img)
    axes[0, cls_idx].set_title(cls_name, fontsize=9, fontweight='bold')
    axes[0, 0].set_ylabel('Original', fontsize=10)

    # Grad-CAM
    axes[1, cls_idx].imshow(cam_image)
    axes[1, cls_idx].axis('off')
    if cls_idx == 0:
        axes[1, 0].set_ylabel('Grad-CAM', fontsize=10)

plt.tight_layout()
plt.savefig('gradcam_visualization.png', dpi=150, bbox_inches='tight')
plt.show()
print('Grad-CAM visualization selesai ✓')

"""## **10. Ringkasan Hasil**"""

import pandas as pd

# Summary table
summary = pd.DataFrame({
    'Kelas'    : CLASS_NAMES,
    'Precision': precision.round(4),
    'Recall'   : recall.round(4),
    'F1-Score' : f1_per.round(4),
    'Support'  : cm.sum(axis=1)
})

print('\n' + '='*65)
print('RINGKASAN HASIL MODEL')
print('='*65)
print(summary.to_string(index=False))
print('='*65)
print(f'Accuracy       : {acc:.4f}  ({acc*100:.2f}%)')
print(f'Macro F1-Score : {macro_f1:.4f}')
print(f"Cohen's Kappa  : {kappa:.4f}")

kappa_interp = (
    'Hampir sempurna (>0.80)' if kappa > 0.80 else
    'Substansial (0.61-0.80)' if kappa > 0.60 else
    'Moderat (0.41-0.60)'     if kappa > 0.40 else
    'Cukup (0.21-0.40)'       if kappa > 0.20 else
    'Lemah (<0.20)'
)
print(f"  → Interpretasi Kappa: {kappa_interp}")

# Cek target capaian
target_acc = 0.85
target_f1_minority = 0.75
minority_classes  = ['rotten', 'unripe', 'empty_bunch']
minority_f1_vals  = {c: f1_per[CLASS_NAMES.index(c)] for c in minority_classes if c in CLASS_NAMES}

print('\n--- Pengecekan Target Capaian ---')
print(f'Target Accuracy ≥ {target_acc:.0%}: {"TERCAPAI" if acc >= target_acc else " BELUM"}  ({acc:.4f})')
for cls, f1v in minority_f1_vals.items():
    status = 'TERCAPAI' if f1v >= target_f1_minority else 'BELUM'
    print(f'Target F1 {cls} ≥ {target_f1_minority:.0%}: {status}  ({f1v:.4f})')

# Save checkpoint final
torch.save({
    'model_state_dict' : model.state_dict(),
    'class_names'      : CLASS_NAMES,
    'accuracy'         : acc,
    'macro_f1'         : macro_f1,
    'kappa'            : kappa,
}, 'palm_ripeness_final.pth')
print('\nModel final tersimpan: palm_ripeness_final.pth ✓')

"""# **validasi**"""

# VALIDASI 1 DATA LEAKAGE CHECK
from pathlib import Path

train_files = {
    Path(x[0]).name.lower()
    for x in train_dataset.samples
}

val_files = {
    Path(x[0]).name.lower()
    for x in val_dataset.samples
}

test_files = {
    Path(x[0]).name.lower()
    for x in test_dataset.samples
}

train_val_overlap = train_files & val_files
train_test_overlap = train_files & test_files
val_test_overlap = val_files & test_files

print("="*50)
print("LEAKAGE CHECK")
print("="*50)

print(f"Train-Val overlap  : {len(train_val_overlap)}")
print(f"Train-Test overlap : {len(train_test_overlap)}")
print(f"Val-Test overlap   : {len(val_test_overlap)}")

if (
    len(train_val_overlap)==0 and
    len(train_test_overlap)==0 and
    len(val_test_overlap)==0
):
    print("\n✓ Tidak ada indikasi leakage")
else:
    print("\n⚠ Ada kemungkinan leakage")

# VALIDASI 2 — OVERFITTING CHECK
train_acc_final = history_p2['train_acc'][-1]
val_acc_final   = history_p2['val_acc'][-1]

gap = train_acc_final - val_acc_final

print("="*50)
print("OVERFITTING CHECK")
print("="*50)

print(f"Train Accuracy : {train_acc_final:.4f}")
print(f"Val Accuracy   : {val_acc_final:.4f}")
print(f"Gap            : {gap:.4f}")

if gap < 0.05:
    print("\n✓ Overfitting rendah")
elif gap < 0.10:
    print("\n⚠ Overfitting ringan")
else:
    print("\n⚠ Overfitting sedang/tinggi")

# VALIDASI 3 — PER CLASS ANALYSIS
report = classification_report(
    all_labels,
    all_preds,
    target_names=CLASS_NAMES,
    output_dict=True
)

df_report = pd.DataFrame(report).transpose()

display(
    df_report[
        ['precision','recall','f1-score','support']
    ].round(4)
)

worst_class = df_report.iloc[:-3]['f1-score'].idxmin()

print("\nKelas dengan performa terendah:")
print(worst_class)
print(
    df_report.loc[
        worst_class,
        ['precision','recall','f1-score']
    ]
)

# VALIDASI 4 — ERROR ANALYSIS
wrong_idx = np.where(
    np.array(all_preds) != np.array(all_labels)
)[0]

print(
    f"Jumlah prediksi salah: {len(wrong_idx)}"
)

fig, axes = plt.subplots(
    3,
    4,
    figsize=(12,9)
)

axes = axes.flatten()

for ax, idx in zip(
    axes,
    wrong_idx[:12]
):

    img_path, true_label = test_dataset.samples[idx]

    img = Image.open(
        img_path
    ).convert("RGB")

    pred_label = all_preds[idx]

    ax.imshow(img)

    ax.set_title(
        f"GT: {CLASS_NAMES[true_label]}\n"
        f"Pred: {CLASS_NAMES[pred_label]}",
        fontsize=9
    )

    ax.axis("off")

plt.tight_layout()
plt.show()